### ISSUE TITLE
Update to patch 15.0.2.33157

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HearthDb#14]
The hsdata was updated to new version 15.0.2.33157 on 2019-08-14
https://github.com/HearthSim/hsdata/commit/85b5a219afe49d5015725c344fd7412945a346b7

**Comment by riQQ** [comment]
What are you trying to say?

**Comment by chucklu** [comment]
When I try to build this library, it's blocked at https://github.com/HearthSim/HearthDb/blob/master/HearthDb/verify.ps1
```Powershell
if ($aVersion -ne $hsdVersion) {
        echo "verify.ps1: verification error 1: assembly version ($assemblyVersion) does not match hsdata ($hsdataVersion)"
    }
```
  
  
And I find this project depends on hsdata repository, currently the project can not pass build because the pre-build event will sync the hsdata automatically.
![image](https://user-images.githubusercontent.com/3004057/63405976-0d6e3c00-c41b-11e9-9e79-8f18623d7444.png)

**Comment by chucklu** [comment]
Since the project build would be blocked by another repository, it would be better if you can arrange build automatically everyday through [cicd](https://en.wikipedia.org/wiki/CI/CD) task.
Or you can check the new commit on hsdata repository by tools daily or manually check?

**Comment by chucklu** [comment]
https://github.com/HearthSim/HearthDb/commit/ec28cca51481b208c44e3b6629690465219fa7cd
