### ISSUE TITLE
The PlayRequirement  section lost since version 16.0.0.37060

### ISSUE THREAD

**Issue by chucklu** [HearthSim/HearthDb#18]
I have checked the history of https://github.com/HearthSim/hsdata, and I found the following section of card GIL_530 was lost.
```xml
<Power definition="00000012-3781-4b7f-bb1d-fd54f645afe9">
			<PlayRequirement param="" reqID="75"/>
		</Power>
```
patch 15.6.2.36393 still has the [PlayRequirement](https://github.com/HearthSim/HearthDb/blob/master/HearthDb/CardDefs/PlayRequirement.cs)  section, when it comes to patch 16.0.0.37060, the section lost.

I would like to file a new issue in hsdata project, but that project hid the issues tab, so I file a new issue here .

**Comment by beheh** [comment]
This was removed from the Hearthstone game data itself. As we don't want to maintain it ourselves it had to be dropped.

**Comment by shinoi2** [comment]
Fine, I will move PlayReq into fireplace.
