### ISSUE TITLE
Is there something I'm missing? This doesn't build.

### ISSUE THREAD

**Issue by BLevyCS** [HearthSim/HearthDb#7]
Do I need something else to make this build? I cloned the repo and brought it into VS 2013, and it doesn't build. It's reporting many syntax errors, including missing semicolons, bad keywords, missing parentheses, and more.

**Comment by judge2020** [comment]
Try 2017, I can compile just fine and [appveyor](https://ci.appveyor.com/project/azeier/hearthdb) builds it just fine on VS 2017.

Note that this is not a standalone application, it's meant to be used as a library in a C# project, mainly [Hearthstone Deck Tracker](/Hearthsim/Hearthstone-Deck-Tracker).

**Comment by BLevyCS** [comment]
I saw that appveyor was building it just fine, which is why I was wondering if it was something I'm missing.

I wanted to learn about how deck codes are serialized and deserialized for my own ideas. I was looking for starting points, since it seems like I need something to pull all the card data from.

**Comment by BLevyCS** [comment]
I saw that appveyor was building it just fine, which is why I was wondering if it was something I'm missing.

I wanted to learn about how deck codes are serialized and deserialized for my own ideas. I was looking for starting points, since it seems like I need something to pull all the card data from.

I can try VS2017 when I get home. Is there anything I can do in 2013 while I'm here?
